/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studioirregular_gaoframework_NativeInterface */

#ifndef _Included_com_studioirregular_gaoframework_NativeInterface
#define _Included_com_studioirregular_gaoframework_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_studioirregular_gaoframework_NativeInterface
 * Method:    NotifyBackPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_NativeInterface_NotifyBackPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_studioirregular_gaoframework_NativeInterface
 * Method:    NotifyAlertDialogResult
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_NativeInterface_NotifyAlertDialogResult
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
