/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studioirregular_gaoframework_MyGLRenderer */

#ifndef _Included_com_studioirregular_gaoframework_MyGLRenderer
#define _Included_com_studioirregular_gaoframework_MyGLRenderer
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_studioirregular_gaoframework_MyGLRenderer
 * Method:    RendererOnSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_MyGLRenderer_RendererOnSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_studioirregular_gaoframework_MyGLRenderer
 * Method:    RendererOnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_MyGLRenderer_RendererOnSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_studioirregular_gaoframework_MyGLRenderer
 * Method:    RendererOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_MyGLRenderer_RendererOnDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
