/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studioirregular_gaoframework_AbsGameActivity */

#ifndef _Included_com_studioirregular_gaoframework_AbsGameActivity
#define _Included_com_studioirregular_gaoframework_AbsGameActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_studioirregular_gaoframework_AbsGameActivity
 * Method:    ActivityOnCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_AbsGameActivity_ActivityOnCreate
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     com_studioirregular_gaoframework_AbsGameActivity
 * Method:    ActivityOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_AbsGameActivity_ActivityOnDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_studioirregular_gaoframework_AbsGameActivity
 * Method:    OnTouchEvent
 * Signature: (FFI)V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_gaoframework_AbsGameActivity_OnTouchEvent
  (JNIEnv *, jobject, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
