/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studioirregular_jadeninja_p1_MainActivity */

#ifndef _Included_com_studioirregular_jadeninja_p1_MainActivity
#define _Included_com_studioirregular_jadeninja_p1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_studioirregular_jadeninja_p1_MainActivity
 * Method:    nativeCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_jadeninja_p1_MainActivity_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_studioirregular_jadeninja_p1_MainActivity
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_studioirregular_jadeninja_p1_MainActivity_nativeDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
